apiVersion: v1
kind: Service
metadata:
  name: sample-maven-project
  namespace: sample-maven-project
spec:
  selector:
    app: sample-maven-project
  ports:
    - name: http
      port: 8080
      targetPort: 8080
